version: "3.8"

services:
  php:
    build:
      context: './php/'
    ports:
      - ${WEB_PORT}
      - ${WEB_SEC_PORT}
    networks:
      - backend
    volumes:
      - ${HOST_PATH}:/var/www/html/
    depends_on:
      - database

  database:
    image: ${MYSQL}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT}
    volumes:
      - ./fixMysqlBug1.cnf:/etc/mysql/conf.d/fixMysqlBug1.cnf
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

networks:
  backend:

