version: "3.8"

services:
  php:
    build:
      context: './php/'
    ports:
      - ${WEB_PORT}
      - ${WEB_SEC_PORT}
    networks:
      - backend
    volumes:
      - ${HOST_PATH}:/var/www/html/
      # - ./proxy/certs:/etc/apache2/ssl/
    depends_on:
      - database

  database:
    image: ${MYSQL}
    # restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT}
    volumes:
      # - ./mysql:/var/lib/mysql
      - ./fixMysqlBug1.cnf:/etc/mysql/conf.d/fixMysqlBug1.cnf
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
  
  # proxy:
  #   image: nginx:1.19.10-alpine
  #   ports:
  #     - ${PROXY_WEB_PORT}
  #     - ${PROXY_WEB_SEC_PORT}
  #   volumes:
  #     - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
  #     - ./proxy/certs:/etc/nginx/certs
  #   depends_on:
  #     - php

networks:
  backend:

